### ISSUE TITLE
Race/Class are not updated past 3.3.5

### ISSUE THREAD

**Issue by angrytoilet** [r-o-b-o-t-o/azerothcore-armory#16]
### Current Behaviour

We are getting errors when viewing any race outside of the "classic 10".  Our Zandalari Trolls are displayed (and named) Troll.  Our Vulpera throw errors when you click on them.  Those are 2 examples.

### Expected behaviour

Click Vulpera > display gear.

### Reproduction steps

1.  Search for a player that is using Vulpera race
2.  Click player to display Armory

### Server operating system

Windows 

### Client operating system and browser

Windows w/ Chrome

### Armory revision

Latest pull from 3 days ago.  Using the latest as of May 3rd 2022 (update from 19 days ago)

### AzerothCore revision (commit hash)

latest.

**Comment by r-o-b-o-t-o** [comment]
Hi there,
This tool is meant to be used with a more or less stock AzerothCore, in order to maintain compatibility for most users. This means that the armory supports only the classes present in the 3.3.5 version of the game.

You will need to edit the following files if you want to support custom classes:
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/tools/fetchdata.ts#L166-L177
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/armory/Utils.ts#L15-L26
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/armory/Utils.ts#L41
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/armory/data/CharacterCustomization.ts#L10
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/armory/controllers/CharacterController.ts#L49-L60
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/src/armory/controllers/CharacterController.ts#L458
https://github.com/r-o-b-o-t-o/azerothcore-armory/blob/8906047a060b610bad599aebff2c9a52fd3a9f72/static/character.hbs#L70-L81

If you'd like to propose a better race handling system that allows for custom classes (maybe by reading `ChrClasses.dbc`?), feel free to open a Pull Request.
